### ISSUE TITLE
Notebooks don't run in Binder

### ISSUE THREAD

**Issue by rozyczko** [EasyScience/EasyDiffractionLib#125]
@celinedurniak tried running EDL notebooks in Binder and they fail with 
```python
ModuleNotFoundError: No module named 'easyCore'
```

**Comment by AndrewSazonov** [comment]
All notepads in the examples/ directory now run as tests in a dedicated CI workflow. Instead of Binder, we now use Google Colab to test easydiffraction without installing anything locally. All notebooks have links to Google Colab on the documentation page: https://docs.easydiffraction.org/lib/how-to-use/
